//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carriage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carriage()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int CarriageId { get; set; }
        public string CarriageContactInfo { get; set; }
        public Nullable<System.DateTime> CarriageDepartureDate { get; set; }
        public Nullable<System.DateTime> CarriageArrivalDate { get; set; }
        public Nullable<int> TransportReference { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
