//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.OrderTable = new HashSet<OrderTable>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeContactInfo { get; set; }
        public string EmployeeExperience { get; set; }
        public Nullable<int> EmployeeStatus { get; set; }
        public Nullable<int> CarriageReference { get; set; }
    
        public virtual Carriage Carriage { get; set; }
        public virtual EmployeeStatusTable EmployeeStatusTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTable { get; set; }
    }
}
